CREATE TABLE project (
    id BIGSERIAL  PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unique_code VARCHAR(8) NOT NULL
);